### PR TITLE
Add .gitignore and remove unnecessary files

### PR DESCRIPTION
**Pull request by OverloadedOrama**
Added a .gitignore file that is based on other Godot ignores. See https://github.com/Orama-Interactive/Pixelorama/pull/234 and https://github.com/github/gitignore/blob/master/Godot.gitignore

This PR also removes the `.import/` directory, as it's unnecessary to exist in the repository, since its contents are generated automatically when editing the project for the first time (see https://github.com/Orama-Interactive/Pixelorama/pull/7).

Finally, the default_env.tres file doesn't need to be here, since these files are, as far as I know, used only in 3D. Signum, and most 2D games/applications, work just fine without it.

### CODE REVIEW

**Comment by MintStudios** [comment]
@OverloadedOrama Yes that seems practical.

**Comment by MintStudios** [comment]
@OverloadedOrama I don't think you should delete export_presets.cfg. Isn't that required to export?

**Comment by OverloadedOrama** [comment]
> @OverloadedOrama I don't think you should delete export_presets.cfg. Isn't that required to export?

Not really, if someone wants to export, the export_presets.cfg file gets generated again when you open the Export window on Godot. It will be empty, of course. If you want, you can keep it, but it's not really important as the users can generate another. However, if you plan on exporting to Android, you must not include the file on the repository, because you'll have sensitive data in there, and it's not a good idea to have them public.

It's good practice to not include export_presets.cfg, unless you have a specific reason to do it.

**Comment by MintStudios** [comment]
OK. And I don't plan on exporting a text editor for android. Thanks.

**Pull request merged**
